[package]
name = "n-body-works"
version = "0.1.0"
edition = "2021"

[dependencies]
egui = "0.31.1"
raw-window-handle = "0.6.2"
egui-wgpu = { version = "0.31.1", features = ["winit"] }
egui-winit = "0.31.1"
winit = "0.30.11"
pollster = "0.4.0"
wgpu = "25.0.2"
bytemuck = "1.23.0"
rand = "0.9.1"
log = "0.4.27"
env_logger = "0.11.8"
glam = "0.30.4"

[build-dependencies]
cmake = "0.1.54"
